<a href="https://colab.research.google.com/github/chayakonchanlun/Multvariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Function

เขียน def ตามด้วยชื่อฟังก์ชั่น

In [ ]:
def function name(input) :

  do_something with  Input to produce Output

  return Output

    function มีส่วนสำคัญทั้งหมด4ส่วน
    1.บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function(): (ขาดไม่ได้)
    2.กำหนดตัวแปรที่จะเป็น input input (ขาดไม่ได้)
    3.ส่วนประมวลผล do_something with input to get output (ขาดไม่ได้)
    4.ส่วน output return Output (ขาดไม่ได้) 

In [ ]:
def print_name(name,surname,ID):
    st=f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    return st
    print('outside function')    

การเรียกใช้

In [ ]:
print_name('ชยากร','จันทร์ลุน','623020517-9')


'ชื่อ ชยากร นามสกุล จันทร์ลุน ID 623020517-9'

ฟังก์ชั่นไม่จำเป็นต้องมี output 

In [ ]:
def print_name2(surname,ID,name):
    st=f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)

ฟังก์ชั่นที่ไม่จำเป็นต้องมีใน Input 

input ของ function ใน python มี2แบบ input ที่จำเป็นต้องใส่กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default) เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_21ines_default(name, surname, ID, grade='F'):
    st=f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2=f'เกรดวิชา Mulivariate >>> {grade}'
    print(st2)

In [ ]:
print_21ines_default('ชยากร','จันทร์ลุน','623020517-9')

ชื่อ ชยากร นามสกุล จันทร์ลุน รหัส 623020517-9
เกรดวิชา Mulivariate >>> F


In [ ]:
print_21ines_default('ชยากร','จันทร์ลุน','623020517-9','A')

ชื่อ ชยากร นามสกุล จันทร์ลุน รหัส 623020517-9
เกรดวิชา Mulivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

    HW3 ให้เขียน function คำนวณจำนวนวินาทีจากเวลาต่อไปนี้
    '14-15-31'
    '13-00-01'
    '05-49-44'
    '00-00-16'
    และปริ้นให้สวยงาม

In [ ]:
def function_time(time):
    st = time.split('-')
    answer = int(st[0]) * 3600 + int(st[1]) * 60 +int(st[2])
    print(f'เวลา {time} คำนวนเป็นจำนวนวินาทีได้เท่ากับ {answer} วินาที ')

In [ ]:
function_time('14-15-31')

เวลา 14-15-31 คำนวนเป็นจำนวนวินาทีได้เท่ากับ 51331 วินาที 


In [ ]:
function_time('13-00-01')

เวลา 13-00-01 คำนวนเป็นจำนวนวินาทีได้เท่ากับ 46801 วินาที 


In [ ]:
function_time('05-49-44')

เวลา 05-49-44 คำนวนเป็นจำนวนวินาทีได้เท่ากับ 20984 วินาที 


In [ ]:
function_time('00-00-16')

เวลา 00-00-16 คำนวนเป็นจำนวนวินาทีได้เท่ากับ 16 วินาที 


เริ่ม 19/1/2564

~panda~

    Numpy-> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)
    Num+py->Number-Numerical+python

    การใช้ package
    1.'''import''' '''ชื่อ package''' #เรียกใช้ package
    2.'''ชื่อ package.ชื่อฟังก์ชัน #เรียกใช้ function

In [2]:
import numpy

data structure->array

สร้าง array (numpy array)

In [3]:
mat_ex1= numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [4]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [5]:
list_ex1=([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [10]:
list_ex1[1][1]

0.1

In [12]:
print(list_ex1)
a=list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


    Matrix Operation
    data 2 แบบ -> matrix (2D array), scalar (ตัวเลขค่าคงที่)

In [13]:
mat_ex1= numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2= numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตัวแหน่งเดียวกันมาบวกกัน
(หน้าตาของ matrix 

---



mat_ex0 = numpy.array([

In [14]:
mat_ex3=mat_ex1+mat_ex2 
print(mat_ex3)
mat_ex4=mat_ex1-mat_ex2 
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


การตรวจสอบขนาดงของ marix 

In [15]:
mat_ex3.shape

(2, 3)

In [16]:
mat_ex3.shape[0]

2

## คูณ matrix (แถวคูณหลัก)
    (หลักของตัวข้างหน้า ต้องเท่ากับแถวของ matrix ตัวข้างหลัง)

    dot product (AAA,x),(x,ZZZ) = (AAA,ZZZ)

In [17]:
 mat_ex1*mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [ ]:
numpy.dot(mat_ex1,mat_ex2)

In [18]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว
matrix.T



In [19]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [22]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(3,2)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

    ##HW4 อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)